
# Task name - used to pick the class to load
task_name: ${task.name}
role: 'protagonist'

# experiment name. defaults to name of training config
experiment: ''

# if set to positive integer, overrides the default number of environments
num_envs: 64
# num_envs: ''

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: 10000

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: True
# test: False
# used to set checkpoint path
checkpoint: '/home/linjiw/Downloads/isaacgym-jackal/isaacgymenvs/runs/Jackal/nn/last_Jackal_ep_10000_rew_16.249006.pth'
# checkpoint: ''
# set to True to use multi-gpu horovod training
multi_gpu: False

wandb_activate: True
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: 'linjiw'
wandb_project: 'isaacgymenvs'
capture_video: False
capture_video_freq: 200
capture_video_len: 100
force_render: True

# disables rendering
headless: False

# set default task and default training config based on task
defaults:
  # - task: Ant
  - task: Jackal
  - train: ${task}PPO
  - hydra/job_logging: disabled

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .

